### ISSUE TITLE
Race condition due to premature Promise keep in listener.

### ISSUE THREAD

**Issue by bbkr** [massa/SSH-LibSSH-Tunnel#2]
`$tunnel-server` promise should be kept whenever `.socket-port` promise is kept, not when `.listen` is started.

Explained here: https://stackoverflow.com/questions/78984529/when-whenever-block-in-react-section-starts-processing-events/78986120#78986120

**Comment by massa** [comment]
This is a nice catch (I was stomped on this, and the client I have for this library was using a `sleep` to evade the race...). Thank you very much! A newer release is following!

**Comment by bbkr** [comment]
Thank you for prompt fix!
